# import kvm1
from xml.etree import ElementTree
import psutil
import libvirt
import pandas as pd
conn=libvirt.open("qemu+SSH://root@10.1.0.150/system")
import psutil
import libvirt
import pandas as pd
conn=libvirt.open("qemu+SSH://root@10.1.0.150/system")
host = conn.getHostname()
print('Hostname:'+host)
fr = psutil.cpu_freq(conn)
# fr.to_csv('NKVM.csv')
print(fr[0])
print(fr[1])
print(fr[2])
print(fr[3])
stats = conn.getCPUStats(0)
# stats.to_csv('NKVM.csv')
print("CPU usage")
print("Kernel:",+stats['kernel'])
print("idle:",+stats['user'])
print("user:",+stats['idle'])
print("iowait:",+stats['iowait'])
buf = conn.getMemoryStats(libvirt.VIR_NODE_MEMORY_STATS_ALL_CELLS)
# buf.to_csv('NKVM.csv')
print("MEMORY usage")
print("Total:",+buf['total'])
print("Free:",+buf['free'])
print("Buffers:",+buf['buffers'])
print("Cached:",+buf['cached'])
dsk = psutil.disk_io_counters(conn)
print(dsk.keys())
print("DISK i/o")
df1 = pd.DataFrame(dsk,columns=['read_count','write_count','read_bytes','write_bytes','read_time','write_time','read_merged_count','write_merged_count','busy_time'])
df1.to_csv('NKVM.csv')
print(df1)

ntk = psutil.net_io_counters(conn)
print("NETWORK i/o")
df = pd.DataFrame(ntk,index=['bytes_sent','bytes_recv','packets_sent','packets_recv','errin','errout','dropin','dropout'])
df.to_csv('NKVM.csv')
print(df)

# fr.to_csv('NKVM.csv')
print(fr[0])
print(fr[1])
print(fr[2])
print(fr[3])
stats = conn.getCPUStats(0)
# stats.to_csv('NKVM.csv')
print("CPU usage")
print("Kernel:",+stats['kernel'])
print("idle:",+stats['user'])
print("user:",+stats['idle'])
print("iowait:",+stats['iowait'])
buf = conn.getMemoryStats(libvirt.VIR_NODE_MEMORY_STATS_ALL_CELLS)
# buf.to_csv('NKVM.csv')
print("MEMORY usage")
print("Total:",+buf['total'])
print("Free:",+buf['free'])
print("Buffers:",+buf['buffers'])
print("Cached:",+buf['cached'])
dsk = psutil.disk_io_counters(conn)
print(dsk.keys())
print("DISK i/o")
df1 = pd.DataFrame(dsk,columns=['read_count','write_count','read_bytes','write_bytes','read_time','write_time','read_merged_count','write_merged_count','busy_time'])
df1.to_csv('NKVM.csv')
print(df1)

ntk = psutil.net_io_counters(conn)
print("NETWORK i/o")
df = pd.DataFrame(ntk,index=['bytes_sent','bytes_recv','packets_sent','packets_recv','errin','errout','dropin','dropout'])
df.to_csv('NKVM.csv')
print(df)

